import type { FlightDeal, PreferenceMemory } from '@/types'

export const mockDeals: FlightDeal[] = [
  {
    id: 'fd001',
    platform: '航旅纵横',
    origin: '北京', originCode: 'BJS',
    destination: '三亚', destinationCode: 'SYX',
    price: 398, originalPrice: 980,
    departDate: '2026-05-01',
    airline: '海南航空', departTime: '07:30', arriveTime: '13:45',
    signals: ['近90天低位', '五一低价'],
    confidence: 'high',
    systemId: 'SYS.042',
    gradientFrom: '#0EA5E9', gradientTo: '#22D3EE',
    verdict: '建议现在买',
  },
  {
    id: 'fd002',
    platform: '飞猪',
    origin: '上海', originCode: 'SHA',
    destination: '大理', destinationCode: 'DLU',
    price: 560, originalPrice: 1200,
    departDate: '2026-04-20',
    airline: '云南航空', departTime: '14:20', arriveTime: '17:55',
    signals: ['符合心理价位', '近期最低'],
    confidence: 'high',
    systemId: 'SYS.117',
    gradientFrom: '#8B5CF6', gradientTo: '#C4B5FD',
    verdict: '建议现在买',
  },
  {
    id: 'fd003',
    platform: '去哪儿',
    origin: '广州', originCode: 'CAN',
    destination: '成都', destinationCode: 'CTU',
    price: 320, originalPrice: 720,
    departDate: '2026-04-25',
    airline: '四川航空', departTime: '09:15', arriveTime: '11:40',
    signals: ['历史新低'],
    confidence: 'medium',
    systemId: 'SYS.208',
    gradientFrom: '#10B981', gradientTo: '#6EE7B7',
    verdict: '可以关注',
  },
  {
    id: 'fd004',
    platform: '携程',
    origin: '北京', originCode: 'BJS',
    destination: '厦门', destinationCode: 'XMN',
    price: 480, originalPrice: 1100,
    departDate: '2026-05-03',
    airline: '厦门航空', departTime: '11:00', arriveTime: '14:30',
    signals: ['近90天低位', '假期前低价'],
    confidence: 'high',
    systemId: 'SYS.334',
    gradientFrom: '#F59E0B', gradientTo: '#FCD34D',
    verdict: '建议现在买',
  },
  {
    id: 'fd005',
    platform: '同程',
    origin: '深圳', originCode: 'SZX',
    destination: '西藏', destinationCode: 'LXA',
    price: 890, originalPrice: 1850,
    departDate: '2026-05-10',
    airline: '西藏航空', departTime: '08:00', arriveTime: '12:25',
    signals: ['季节性低点', '符合偏好'],
    confidence: 'medium',
    systemId: 'SYS.456',
    gradientFrom: '#3B82F6', gradientTo: '#93C5FD',
    verdict: '可以关注',
  },
]

export const mockMemories: PreferenceMemory[] = [
  {
    id: 'm001', field: 'price_anchor', label: '心理价位',
    value: '¥600 以内', source: 'auto',
    updatedAt: '3天前', accentColor: '#22C55E', rotation: '-1deg',
  },
  {
    id: 'm002', field: 'preferred_origins', label: '常用出发地',
    value: '北京、上海', source: 'manual',
    updatedAt: '6天前', accentColor: '#1B2B5E', rotation: '2deg',
  },
  {
    id: 'm003', field: 'preferred_destinations', label: '想去的地方',
    value: '三亚、大理、成都', source: 'auto',
    updatedAt: '1天前', accentColor: '#F59E0B', rotation: '-2deg',
  },
  {
    id: 'm004', field: 'travel_window', label: '出行时间偏好',
    value: '周末 / 法定假日', source: 'manual',
    updatedAt: '10天前', accentColor: '#8B5CF6', rotation: '1.5deg',
  },
  {
    id: 'm005', field: 'cabin_preference', label: '舱位偏好',
    value: '经济舱', source: 'auto',
    updatedAt: '15天前', accentColor: '#0EA5E9', rotation: '-1.5deg',
  },
]

export const missedDeal = mockDeals[0]
export const hotDeals = mockDeals.slice(0, 4)
